services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Longman\TelegramBot\Telegram:
    class: Longman\TelegramBot\Telegram
    arguments:
      - '%env(TELEGRAM_BOT_TOKEN)%'
      - '%env(TELEGRAM_BOT_USERNAME)%'
