services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Sokil\TelegramBot\Command\:
    resource: '../../Command'

  Sokil\TelegramBot\Command\StartPushCommand:
    class: Sokil\TelegramBot\Command\StartPushCommand
    arguments:
      - '@Sokil\TelegramBot\Service\TelegramBotClient\TelegramBotClientInterface'
      - '@router'
      - '%env(HTTP_SERVER_PORT)%'
