services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  config_file_locator:
    class: Symfony\Component\Config\FileLocator
    arguments:
      - ['%kernel.config_dir%']

  event_dispatcher:
    public: true
    class: Symfony\Component\EventDispatcher\EventDispatcher

  Symfony\Component\EventDispatcher\EventDispatcherInterface: '@event_dispatcher'

  event_loop:
    class: React\EventLoop\LoopInterface
    factory: [React\EventLoop\Factory, create]

  React\EventLoop\LoopInterface: '@event_loop'

  Sokil\TelegramBot\Service\:
    resource: '../../Service'

  logger:
    class: Sokil\TelegramBot\Service\Logger\ConsoleLogger
    public: true

  Psr\Log\LoggerInterface: '@logger'
