services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Sokil\TelegramBot\Service\:
    resource: '../../Service'

  Sokil\TelegramBot\ConversationManager\ConversationDispatcher:
    arguments:
      -
        Sokil\TelegramBot\Conversation\WhoAmIConversation: "/whoami"

  Sokil\TelegramBot\Conversation\:
    resource: '../../Conversation'

