services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  config_file_locator:
    class: Symfony\Component\Config\FileLocator
    arguments:
      - ['%kernel.config_dir%']

  Symfony\Component\EventDispatcher\EventDispatcherInterface:
    class: Symfony\Component\EventDispatcher\EventDispatcher

  Sokil\TelegramBot\Service\:
    resource: '../../Service'

