services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  ####################################################################
  # Common services                                                  #
  ####################################################################
  Sokil\TelegramBot\Service\ConversationManager\ConversationDispatcher:
    class: Sokil\TelegramBot\Service\ConversationManager\ConversationDispatcher
    public: false
    arguments:
      - [] # conversations collection
      - '@Sokil\TelegramBot\Service\ConversationManager\ConversationCollection\ConversationCollectionInterface'
      - '@service_container'
      - '@Symfony\Component\Workflow\Registry'

  Sokil\TelegramBot\Service\ConversationManager\ConversationCollection\ConversationCollectionInterface:
    public: false
    class: Sokil\TelegramBot\Service\ConversationManager\ConversationCollection\InMemoryConversationCollection

  ####################################################################
  # Conversations                                                    #
  ####################################################################
  Sokil\TelegramBot\Conversation\:
    resource: '../../Conversation/'

  Sokil\TelegramBot\Conversation\HelpConversation:
    class: Sokil\TelegramBot\Conversation\HelpConversation
    arguments:
      - '@Sokil\TelegramBot\Service\TelegramBotClient\TelegramBotClientInterface'
      - '@resource_file_locator'
