parameters:
  router.request_context.host: '%env(HTTP_HOSTNAME)%'
  router.request_context.scheme: 'https'
  router.request_context.base_url: ''

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  router.config_file_loader:
    class: Symfony\Component\Routing\Loader\YamlFileLoader
    arguments:
      - '@config_file_locator'

  router.request_context:
    class: Symfony\Component\Routing\RequestContext
    arguments:
      - '%router.request_context.base_url%'
      - 'GET'
      - '%router.request_context.host%'
      - '%router.request_context.scheme%'

  Symfony\Component\Routing\RouterInterface: '@router'

  router:
    class: Symfony\Component\Routing\Router
    arguments:
      - '@router.config_file_loader'
      - 'routes.yml'
      - {cache_dir: '%kernel.cache_dir%/'}
      - '@router.request_context'

  request_handler.locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    tags: ['container.service_locator']
    arguments:
      -
        Sokil\TelegramBot\HttpRequestHandler\TelegramWebHookRequestHandler: '@Sokil\TelegramBot\HttpRequestHandler\TelegramWebHookRequestHandler'

  Sokil\TelegramBot\Service\HttpServer\HttpServer:
    class: Sokil\TelegramBot\Service\HttpServer\HttpServer
    arguments:
      - '@router'
      - '@request_handler.locator'
      - '%env(HTTP_SERVER_PORT)%'

  Sokil\TelegramBot\HttpRequestHandler\:
    resource: '../../HttpRequestHandler'