parameters:
  router.request_context.host: '%env(HTTP_HOSTNAME)%'
  router.request_context.scheme: 'https'
  router.request_context.base_url: ''

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ####################################################################
  # Routing requests to controller                                   #
  ####################################################################
  router.config_file_loader:
    class: Symfony\Component\Routing\Loader\YamlFileLoader
    arguments:
      - '@config_file_locator'

  router.request_context:
    class: Symfony\Component\Routing\RequestContext
    arguments:
      - '%router.request_context.base_url%'
      - 'GET'
      - '%router.request_context.host%'
      - '%router.request_context.scheme%'

  Symfony\Component\Routing\RouterInterface: '@router'

  router:
    class: Symfony\Component\Routing\Router
    arguments:
      - '@router.config_file_loader'
      - 'routes.yml'
      - {cache_dir: '%project.cache_dir%/'}
      - '@router.request_context'

  ####################################################################
  # HTTP server and locator of HTTP request handlers (controllers)   #
  ####################################################################
  Sokil\TelegramBot\Service\HttpServer\HttpServer:
    class: Sokil\TelegramBot\Service\HttpServer\HttpServer
    arguments:
      - '@event_loop'
      - '@router'
      - '@http_request_handler.locator'

  http_request_handler.locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    tags: ['container.service_locator']
    arguments:
      # map HTTP request handler class name to it's service id
      -
        Sokil\TelegramBot\HttpRequestHandler\TelegramWebHookRequestHandler: '@Sokil\TelegramBot\HttpRequestHandler\TelegramWebHookRequestHandler'

  ####################################################################
  # Collection of HTTP request handlers, located by                  #
  # http_request_handler.locator                                     #
  ####################################################################
  Sokil\TelegramBot\HttpRequestHandler\:
    resource: '../../HttpRequestHandler'