services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  workflow.registry:
    class: Symfony\Component\Workflow\Registry

  Symfony\Component\Workflow\Registry: '@workflow.registry'

  workflow.abstract:
    class: Symfony\Component\Workflow\Workflow
    abstract: "true"
    public: "true"
    arguments:
      - # workflow definition
      - null # marking store
      - event_dispatcher
      - # name

  state_machine.abstract:
    class: Symfony\Component\Workflow\StateMachine
    abstract: "true"
    public: "true"
    arguments:
      - # workflow definition
      - null # marking store
      - event_dispatcher
      - # name

  workflow.marking_store.multipletelegram_state:
    class: Symfony\Component\Workflow\MarkingStore\MultipleStateMarkingStore
    abstract: true

  workflow.marking_store.single_state:
    class: Symfony\Component\Workflow\MarkingStore\SingleStateMarkingStore
    abstract: true
