services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Symfony\Component\Workflow\Registry:
    class: Symfony\Component\Workflow\Registry

  workflow.abstract:
    class: "Symfony\Component\Workflow\Workflow"
    abstract: "true"
    public: "true"

  state_machine.abstract:
    class: "Symfony\Component\Workflow\StateMachine"
    abstract: "true"
    public: "true"
