workflows:
  conversation.help:
    type: 'state_machine'
    marking_store:
      type: single_state'
      arguments:
        - 'state'
    supports:
      - \Sokikl\TelegramBot\Conversation\HelpConversation
    initial_place: menu_not_shown
    places:
      - menu_not_shown
      - menu_shown
      - menu_item_clicked
      - menu_item_shown
    transitions:
      show_meny:
        from: menu_not_shown
        to: menu_shown